### ISSUE TITLE
Component not updating after changing data

### ISSUE THREAD

**Issue by nicosoutn2014** [DTupalov/react-material-ui-datatable#19]
Hi, when I change an item in the users array, the datatable is not re-rendering with the updated data, am I missing something? here's my code:

`<ReactMUIDatatable
     title={'Lista de Usuarios'}
     data={users}
     columns={columns}
     perPage={15}
     toolbarSelectActions={this.customToolbarSelectActions}
     onStateChanged={this.handleStateChanged}
/>`

**Comment by DTupalov** [comment]
Hi!
This component is fully uncontrolled, so it don't apply new props, if it was rendered.

You can use pattern [fully uncontrolled with a key](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) as React team recommended. A `key` will be as a version of your `users` data, if array was changed, then `key` need to increment and will render new table component. You can use `onStateChanged` to save current state (i.e. page, perPage and etc.), to apply this state, when `key` will increment

Example I will give you later

**Comment by DTupalov** [comment]
Here is an example
https://codesandbox.io/embed/react-material-ui-datatable-p7ktr

Take a look in `Demo.js` module the `Page` component. Here I've quickly implemented pattern with `key`, to update uncontrolled component.

Try to change page, perPage in the table, and then click on button "CHANGE USERS ONCE". It will apply new `users` array, but state of the table wouldn't change.

**Comment by DTupalov** [comment]
I hope example above solved the problem.
