### ISSUE TITLE
No data found for empty result of search

### ISSUE THREAD

**Issue by Way-U-Need** [DTupalov/react-material-ui-datatable#21]
empty table rendered when search string was not found I want to add label as  No data Found for this case.

**Comment by DTupalov** [comment]
Yes, this is nice feature, will add in next release on this week.

**Comment by DTupalov** [comment]
OK, I've added and published to npm v2.0.0-alpha.30
`npm install react-material-ui-datatable@2.0.0-alpha.30 --save-exact`

Now it displays `No matches` if no data found by default.
You can localize it and you can pass your own component to display text (see [doc](../#reactmuidatatables-api) for `localization` and  `customNoMatches`)
